#!/usr/bin/env bash

#	Simple script to hide/unhide polybar
#   Author: z0mbi3
#	url: https://github.com/gh0stzk


function hide() {

		polybar-msg cmd hide | bspc config top_padding 0 | bspc config bottom_padding 0

}

function unhide() {

		# polybar-msg cmd show | bspc config top_padding 40  
		polybar-msg cmd show  

}

   case $1 in
		-h | --hide | hide)
			hide
			exit;;
		-u | --unhide | unhide)
			unhide
			exit;;
			*) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
