#!/run/current-system/sw/bin/bash
file=$1
w=$2
h=$3
x=$4
y=$5

preview() {
  if [[ $(echo $TERM) == "xterm-kitty" ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  else
    mediainfo "$file"
  fi
  exit 1
}

TEMPDIR=~/.cache

file="$1"; shift
case "$(basename "$file" | tr '[A-Z]' '[a-z]')" in
	*.tar*) tar tf "$file" ;;
	*.zip) unzip -l "$file" ;;
	*.rar) unrar l "$file" ;;
	*.7z) 7z l "$file" ;;
	*.avi|*.mp4|*.mkv)
		thumbnail="$TEMPDIR/thumbnail.png"
		ffmpegthumbnailer -i "$file" -o "$thumbnail" -s 900
		preview "$thumbnail"
		;;
	*.pdf)
		thumbnail="$TEMPDIR/thumbnail"
		pdftocairo -png -singlefile -rx 120 -ry 120  "$file" "$thumbnail"
		preview "$thumbnail.png"
		;;
	*.jpg|*.jpeg|*.png|*.webp|*.gif)
		preview "$file"
		;;
	*.ttf|*.otf|*.woff)
		thumbnail="$TEMPDIR/thumbnail.png"
		fontpreview -i "$file" -o "$thumbnail"
		preview "$thumbnail"
		;;
	*.svg)
		thumbnail="$TEMPDIR/thumbnail.png"
		convert "$file" "$thumbnail"
		preview "$thumbnail"
		;;
	*.js | *.py | *.c | *.sh | .zshrc | *.csv|  \
  *.nix| *.lock | *.txt | *.md | *.json | *.html | *.css | \
  *.astro | *.jsx | *.tex | .bash_profile | .bashrc | .gitconfig | \
  *.profile | *.env | .zprofile | *.conf | .gitignore | bspwmrc | \
  *.jsonc | dunstrc | config | *.list | *toml )
    bat --color always --style header --style snip --style changes --style header "$file"
		;;
	*) mediainfo "$file" ;;
esac
return 127 # nonzero retcode required for lf previews to reload
