#! /bin/sh
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
# 

PATH="$HOME/.config/scripts:$PATH" 
pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output eDP-1 --mode 2880x1800 --primary --scale 0.8

if [[ $(xrandr -q |grep 'HDMI2 connected') ]]; then 
  xrandr --output HDMI2 --mode 1920x1080 --below HDMI1
fi

notify-send -u low "󰯉  welcome 󰯉 " &
start-up &

bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor HDMI2 -d 󰯉   

bspc config normal_border_color "#24273a"
bspc config focused_border_color "#6e738d"

bspc config border_width        2 
bspc config window_gap          10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a brave desktop='^3' follow=on
# bspc rule -a discord desktop='^4' follow=on
# bspc rule -a zathura state=tiled desktop='^3'
bspc rule -a Zathura state=tiled

